apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - image: gcr.io/microservice-assignment/frontend:1.1
        name: frontend
        ports:
        - containerPort: 3000
          name: http-server